.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2021 hufeng <hufeng@uniontech.com>,
.\"
.TH "deepin-log-viewer" "1" "2021-3-11" "Deepin"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
deepin-log-viewer \- log viewer for deepin.
.SH SYNOPSIS
deepin-log-viewer [OPTIONS...]
.SH DESCRIPTION
Log Viewer is a useful tool for viewing system logs.
.PP
Log viewer is a tool that collects logs generated when an application is running, for example, logs generated when operating system and applications start up and run. You can do trouble-shooting and solve        
problems quickly by analyzing logs.
.SH OPTIONS
.PP
Note: file(s) + command
.PP
-h,--help      Displays this help.
.PP
-v,--version   Displays version information.
.SH SEE ALSO
https://github.com/linuxdeepin/deepin-log-viewer
.SH AUTHOR
.PP
.B deepin-log-viewer
is written by Deepin Technology Co., Ltd.
.PP
This manual page was written by
.MT linxun@\:uniontech.com
Lin Xun
.ME
for the Debian Project (but may be used by others)
