.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2021 hufeng <hufeng@uniontech.com>,
.\"
.TH "logViewerTruncate" "1" "2021-3-26" "Deepin"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
logViewerTruncate \- Enlarge and shrink log files.
.SH SYNOPSIS
logViewerTruncate [OPTIONS...]
.SH DESCRIPTION
Enlarge and shrink log files.
.PP
Enlarge and shrink log files.
.SH OPTIONS
.PP
Note: file(s) + command
.PP
.SH SEE ALSO
https://github.com/linuxdeepin/deepin-log-viewer
.SH AUTHOR
.PP
.B deepin-log-viewer
is written by Deepin Technology Co., Ltd.
.PP
This manual page was written by
.MT linxun@\:uniontech.com
Lin Xun
.ME
for the Debian Project (but may be used by others)
